typedef unsigned char byte;
typedef unsigned long DWORD;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned char bool;
typedef struct {
	ushort cbmsg;
	ushort fmid;
	ushort ibszGameName;
	ushort cbszGameName;
	ushort ibrgSquadIDs;
	ushort cbrgSquadIDs;
	ushort ibszGameDetailsFiles;
	ushort cbszGameDetailsFiles;
	ushort ibszIGCStaticFile;
	ushort cbszIGCStaticFile;
	ushort ibszServerName;
	ushort cbszServerName;
	ushort ibszServerAddr;
	ushort cbszServerAddr;
	ushort ibszPrivilegedUsers;
	ushort cbszPrivilegedUsers;
	ushort ibszServerVersion;
	ushort cbszServerVersion;
	DWORD dwPort;
	DWORD dwCookie;
	uint dwStartTime;
	short nMinRank;
	short nMaxRank;
	uint nNumPlayers : 11;
	uint nNumNoatPlayers : 11;
	uint nMaxPlayersPerGame : 11;
	uint nMinPlayersPerTeam : 8;
	uint nMaxPlayersPerTeam : 8;
	uint nTeams : 3;
	bool fCountdownStarted : 1;
	bool fInProgress : 1;
	bool fMSArena : 1;
	bool fScoresCount : 1;
	bool fInvulnerableStations : 1;
	bool fAllowDevelopments : 1;
	bool fLimitedLives : 1;
	bool fConquest : 1;
	bool fDeathMatch : 1;
	bool fCountdown : 1;
	bool fProsperity : 1;
	bool fArtifacts : 1;
	bool fFlags : 1;
	bool fTerritorial : 1;
	bool fGuaranteedSlotsAvailable : 1;
	bool fAnySlotsAvailable : 1;
	bool fSquadGame : 1;
	bool fEjectPods : 1;
} LobbyInfoMsg;